Add bare (no container) install for NCI
MetOffice/ngmo-environments pull request #14
Opened 2024-12-19 04:43 UTC by ScottWales

Add an installation method not using a container at NCI. This can help during package development as all of the Spack builds are on the local filesystem rather than the compute nodes' temporary disks so inspection is easier. It has the downside of installs having a much higher inode count.

To the user the container and bare environments appear exactly the same, in both cases the envrun script will ensure the environment is loaded for a command.

2025-01-08 02:29 UTC, ScottWales commented
Fixed some incompatibilities with using packages built for the container in a bare install. @hiker could you please give the bare install a go and let me know how it  goes?

2025-02-07 07:15 UTC, hiker commented
@ScottWales Now I get:
```
UN spack concretize --fresh
==> Error: cannot load package 'blitz' from the 'ngmo' repository: FilePatch: Patch file fujitsu_compiler_specfic_header.patch for package ngmo.blitz does not exist.
```

I did a clean rebuild (after previously trying to just update), same effect.

Directory: /scratch/dp9/jxh903/ngmo-envs

2025-02-13 05:40 UTC, ScottWales commented
That's my mess up with git I think - I put some changes in the wrong branch. I've force-pushed a fix, you may need to delete your local branch to pick it up:
```
git checkout main
git branch -D nci-bare
git checkout nci-bare
```

2025-02-21 14:15 UTC, hiker requested changes
I finally got it working (and I also realised that messages from this repo got filtered into the wrong folder, so I didn't notice your answer in time ... apologies).

I do have one problem though: the intel compilers are not in the path. E.g.:
```
[jxh903@gadi-login-07 ~]$ mpif90 -show
/apps/intel-ct/2021.10.0/compiler/linux/bin/intel64/ifort -I/apps/openmpi/4.1.5/include -I/apps/openmpi/4.1.5/include/Intel -L/apps/openmpi/4.1.5/lib -L/apps/openmpi/4.1.5/lib/Intel -L/system/lib64 -Wl,-rpath=/apps/openmpi/4.1.5/lib -L/apps/intel-oneapi/compiler/2023.2.0/linux/compiler/lib/intel64_lin -Wl,-rpath=/apps/intel-oneapi/compiler/2023.2.0/linux/compiler/lib/intel64_lin -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

[jxh903@gadi-login-07 ~]$ ifort
bash: ifort: command not found
```
Fab relies on being able to run the wrapped compiler to make certain versions are consistent (e.g. it verifies that `mpif90-ifort` does indeed return the same version as `ifort`, to early detect if e.g. the wrong mpif90 wrapper is being started). Adding the intel compiler to the path fixes this, but I think the plain compilers should be available in the environment.

2025-02-23 22:54 UTC, ScottWales commented
I can add this - but if you're after consistency then it may be better to have fab read the output of `mpif90 -showme:command` rather than relying on `$PATH`

2025-02-23 23:46 UTC, hiker commented
> I can add this - but if you're after consistency then it may be better to have fab read the output of `mpif90 -showme:command` rather than relying on `$PATH`

I believe this is an OpenMPI only command, and I wouldn't want to have different implementation of `mpif90` for different MPI versions :(  Plus, I think in general icc etc should be available, since even LFRic can be compiled without mpi (`-DNO_MPI`). Admittedly, you could still use `mpif90` to compile non-MPI programs ;)  People might also want to use other Intel programs (though I have to admit I am not that familiar with them ;) ).

Is there a disadvantage of adding the intel paths? I could of course add an option to not test the consistency (and switch this in our NCI-specific setup)(

2025-02-23 23:56 UTC, ScottWales commented
Only disadvantage is complexity, it should be doable. Also `$FC` etc. should be defined correctly in the environment to the full paths.

2025-02-24 00:27 UTC, ScottWales commented
Nice and simple solution, just add `dirname $CC` to $PATH

2025-02-24 23:44 UTC, hiker commented
> Only disadvantage is complexity, it should be doable. Also `$FC` etc. should be defined correctly in the environment to the full paths.

Well, I want to get rid of the implicit usage of `$FC` etc, instead I prefer the solution that users use a command line option `-fc $FC` - just to make it much more visible where settings come from (Baf will still use `$FC` as default fallback, so I am not breaking stuff :) ). 

ATM, having a full path in `$FC` would not work, but I have opened a ticket for that (https://github.com/MetOffice/lfric-baf/issues/20) ... I actually thought I already had one, since I was aware of this issue :(

The standard gadi modules do not have the full path, so I only realised that problem later :). Fab is using the executable name in its naming, e.g. `mpif90-gfortran` will inherit from the compiler `gfortran`. So I would need to distinguish between `name` and `path`. 

But seeing in your next comment that it was easy to fix, I really prefer this solution - esp. since it makes the environment slightly more generic. Thanks

2025-02-26 01:52 UTC, hiker commented
Thanks a lot for supporting the changes. The environment now built correctly, and was also able to compile LFRic apps. Proceeding to merge.
(for anyone else using FAB: for now you need to unset FC, CC, LD, since they include the full path, which we still need to support in Fab).

2025-02-26 01:53 UTC, hiker approved these changes
Works now. Thanks!

2025-02-26 01:54 UTC, merged